-- Auto-generated upgrade to embed latest disposable domain data

-- Source: https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf

insert into @extschema@.disposable_email_domains(domain) values
('00jac.com'),
('10minmail.org'),
('10minute.email'),
('5ixmonth.xyz'),
('5xu.vn'),
('6gdfg.zone.id'),
('adsensekorea.com'),
('ai100999.com'),
('ankiclub.space'),
('arcadium.lat'),
('baechecker.com'),
('baipiaodashen.cloud-ip.cc'),
('banancaocap.com'),
('bhana.xyz'),
('bokgumail.kr'),
('capcvt.es'),
('clickcore99.click'),
('developtool.app'),
('dgdf.cc'),
('docash.app'),
('fgmail.cyou'),
('gmailxyz.bond'),
('gokublue.me'),
('icloulb.com'),
('indoxs.bond'),
('jika.gg'),
('mailxyz.cyou'),
('metajaya.biz.id'),
('mirasync.tokyo'),
('mmo365.store'),
('monyal.shop'),
('muataikhoan.info'),
('musicflow.buzz'),
('nevanata.com'),
('nondon.store'),
('okcx.edu.rs'),
('outlooks.bond'),
('pp-tw.cc'),
('privo.edu.pl'),
('rua.pp.ua'),
('satorix.id'),
('sedekah-mudah.com'),
('sengkuni.dedyn.io'),
('starlight.store'),
('theboys.cyou'),
('travelovelinka.club'),
('treterter.shop'),
('tuku26012023.xyz'),
('us-x.top'),
('utkarsh.tech'),
('xgmail.bond'),
('xhotmail.cyou'),
('xn--5nx.cc'),
('yahoox.cyou'),
('yangzhong-sfd.cc'),
('zikzak.site')
ON CONFLICT (domain) DO NOTHING;
