-- Auto-generated upgrade to embed latest disposable domain data

-- Source: https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf

insert into @extschema@.disposable_email_domains(domain) values
('66b1it.eu.org'),
('94an.com'),
('airhemp.com'),
('bitrealm.in'),
('bowlfuel.com'),
('brazbuzii.online'),
('corridor.bond'),
('crybio.com'),
('daugr.com'),
('dd2car.com'),
('euroallsports.org.uk'),
('evairo.web.id'),
('fanzher.com'),
('fidhost.com'),
('gcptoday.xyz'),
('godulygmail.com'),
('harpix.org.uk'),
('hebase.com'),
('herlan.co.uk'),
('hulkteam.cyou'),
('iraqedu.online'),
('jamesat.biz.id'),
('jamesat.my.id'),
('jbsze.net'),
('kathrynis.my.id'),
('kathrynis.web.id'),
('kjkpc.net'),
('liondapt.com'),
('mapsguy.com'),
('mediseat.com'),
('neowd.com'),
('nextpomi.dynv6.net'),
('nygrenrealty.com'),
('owovo.site'),
('peterhe-ai.bond'),
('prorises.com'),
('radioastronomynet.com'),
('relayne.top'),
('robustq.com'),
('rosella.my.id'),
('slotbeer.com'),
('vuv.indevs.in'),
('wandouyu.run'),
('xgcpking.space'),
('yopm.zone.id')
ON CONFLICT (domain) DO NOTHING;
