-- Auto-generated upgrade to embed latest disposable domain data

-- Source: https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf

delete from @extschema@.disposable_email_domains
where domain in (
  'iwi.net'
);

insert into @extschema@.disposable_email_domains(domain) values
('20253025.xyz'),
('636364.xyz'),
('792792.xyz'),
('971007.xyz'),
('aisub.store'),
('aizhongzhuan.cc'),
('bilingva-ca.store'),
('bjvc.top'),
('codexrip.vip'),
('cxioms.help'),
('dalanshu.org'),
('digimaster.bond'),
('dulichdatlanh.com'),
('dulichdatlanh.vn'),
('emalupe.com'),
('exzork.sbs'),
('fbb.linkpc.net'),
('fdpbnzx.cn'),
('ffps.fun'),
('fsotl.icu'),
('futcost.online'),
('futcost.ru'),
('ickletonrelief.shop'),
('icotz.com'),
('inderpalsandhu.com'),
('kampret.asia'),
('klut.io'),
('kuromee.com'),
('kuromee.store'),
('lastexile.site'),
('lemonkk.cn'),
('leoguio.site'),
('loveuu.xyz'),
('mamangbadrut.site'),
('mikumirai.top'),
('moldind.help'),
('mopess.help'),
('nomomail.com'),
('norovpn.site'),
('omonomon.shop'),
('orwpaztm.cfd'),
('patientlecadet.online'),
('priyo.edu.pl'),
('qqcomeback.me'),
('sampsave.tech'),
('skyhope666.shop'),
('socialtrash.online'),
('sylnetdns.site'),
('sylnetgcp.top'),
('temp-mail.edu.rs'),
('tempemail.nyc.mn'),
('twskyhopenb.shop'),
('ultralabs24.store'),
('urbanvalore.info'),
('veo3ultra.sbs'),
('xmisom.help'),
('xn--ai-ry2ck37oorv.com'),
('xn--di5au2k.shop'),
('ziyoupi.asia'),
('zrufe.com')
ON CONFLICT (domain) DO NOTHING;
