-- Auto-generated upgrade to embed latest disposable domain data

-- Source: https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf

insert into @extschema@.disposable_email_domains(domain) values
('020307.xyz'),
('apexnovaser.com'),
('arkoo.site'),
('aumails.us'),
('bar-ton.store'),
('buddyfly.top'),
('capcut.space'),
('coralhost.my'),
('dailynove.com'),
('docse.site'),
('emailasia1.com'),
('emailjps.com'),
('emailuae.com'),
('gdfgergrer.online'),
('hilmipremindo.com'),
('hohohim.com'),
('jiongguo.top'),
('kawneha.site'),
('kintil.buzz'),
('kkkoouy.cyou'),
('lanuiopl.bond'),
('lxydawang.top'),
('makeraura.online'),
('nexarshop.store'),
('opihhushdjn.cyou'),
('powerdea.me'),
('reapsa.com'),
('runcubesapps.id'),
('ryuu.codes'),
('sendokai.click'),
('shengxia.asia'),
('sterlingpointco.com'),
('taischaves.com'),
('thispy.top'),
('thuongxg.com'),
('tramynguyen.net'),
('watsawang.com'),
('wintersgf.store'),
('wwtykkm.bond'),
('xazymarcie.space')
ON CONFLICT (domain) DO NOTHING;
