-- Auto-generated upgrade to embed latest disposable domain data

-- Source: https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf

insert into @extschema@.disposable_email_domains(domain) values
('4save.net'),
('acc1s.com'),
('acc1s.net'),
('accclone.com'),
('akunlama.com'),
('aliban.org'),
('awesomesaucemail.org'),
('beelsil.com'),
('bookgame.org'),
('cdnmia.com'),
('choichay.com'),
('cloud-temp.com'),
('coffeejadore.com'),
('connho.com'),
('contaco.org'),
('dulich84.com'),
('eacademia.uk'),
('emailcoffeehouse.com'),
('emailracc.com'),
('emailtik.com'),
('fbhotro.com'),
('hetzez.com'),
('imfaya.com'),
('kenhphim.net'),
('ket-qua.org'),
('kontoko.org'),
('libinit.com'),
('maillog.uk'),
('meocon.org'),
('mikfarm.com'),
('mikrotikvn.com'),
('mokook.com'),
('nhmvn.com'),
('nickmxh.com'),
('pippoc.com'),
('pongpong.org'),
('s3k.net'),
('sonphuongthinh.com'),
('taomail.web.id'),
('tatadidi.com'),
('tenhub.uk'),
('tikmail.org'),
('tiktakgrab.com'),
('tmailor.net'),
('tokmail.net'),
('trangzim.uk'),
('tsmtp.org'),
('tubeemail.com'),
('vertexinbox.com'),
('vinaemail.com'),
('x1ix.com'),
('xehop.org'),
('yomand.store'),
('zozozo123.com')
ON CONFLICT (domain) DO NOTHING;
