-- Auto-generated upgrade to embed latest disposable domain data

-- Source: https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf

insert into @extschema@.disposable_email_domains(domain) values
('2bd.net'),
('aisubpro.click'),
('beatbok.online'),
('dino.icu'),
('doreact.com'),
('friday12.store'),
('graphicbulk.site'),
('graphicenda.site'),
('hanghai232.shop'),
('hqpdf.com'),
('huytuyen.click'),
('jejes.de'),
('laulund.info'),
('launders.money'),
('linkpc.net'),
('liopsacac.shop'),
('marineso.com'),
('midwestpride.org'),
('narrowment.com'),
('newmano.store'),
('nosubcriber.shop'),
('nvqt304.xyz'),
('oldao.com'),
('omnilog.space'),
('pbhak.dev'),
('pozima.rest'),
('ravavo.bond'),
('roybl.com'),
('run.place'),
('salakoais.shop'),
('srame.com'),
('trandigabapoe.shop'),
('vutrugay.org'),
('work.gd'),
('x-clone.asia'),
('xbrok.com'),
('xclone.asia'),
('yeummo.io.vn')
ON CONFLICT (domain) DO NOTHING;
