name: Update disposable email domains

on:
  schedule:
    - cron: '0 12 * * 1' # Every Monday at 12:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Generate seed SQL from upstream blocklist (for diffing)
        run: node scripts/update_disposable_domains.js

      - name: Bump extension version and generate upgrade if blocklist changed
        run: |
          if [ -n "$(git status --porcelain email_guard/seed/disposable_email_domains.sql)" ]; then
            node scripts/bump_email_guard_version.js
          else
            echo "Blocklist unchanged; skipping version bump"
          fi

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add email_guard/seed/disposable_email_domains.sql email_guard/*.sql email_guard/email_guard.control
            git commit -m "chore(email_guard): refresh blocklist and bump version if needed"
            git push
          else
            echo "No changes to commit"
          fi
